### ISSUE TITLE
Any future?

### ISSUE THREAD

**Issue by dumblob** [phil-de-choc/pcastli#2]
Hi, newbie here.

1. Any plans for the future development?

2. Is this being used somewhere in production?

3. Could this be compiled into a binary or does the language semantics allow only for interpretation in a virtual machine?

**Comment by phil-de-choc** [comment]
Hello,
For now, I don't have any new development ideas.
If someone is using it in production, I haven't been told.
I doubt this interpreter could be made to a compiler, because there has to be a dynamic data structure representing the syntax tree of the code.

**Comment by dumblob** [comment]
Thanks for prompt answers! Closing as there are no more actionable items :wink:.
